package programinventorysenjatauas;

import programinventorysenjatauas.Config;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable.PrintMode;
import java.awt.print.PrinterException;
import java.text.MessageFormat;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author GalihPC
 */
public class FormSenjata extends javax.swing.JFrame {

    /**
     * Creates new form FormSenjata
     */
    public FormSenjata() {
        initComponents();
        setLocationRelativeTo(null);
        this.ShowData();
    }
    
    private DefaultTableModel tabelSenjata;
    private String SQL; 

    public void ShowData(){
        tabelSenjata = new DefaultTableModel();
        tabelSenjata.addColumn("ID");
        tabelSenjata.addColumn("Nama");
        tabelSenjata.addColumn("Jenis");
        tabelSenjata.addColumn("Jumlah Magazine");
        tabelSenjata.addColumn("Tanggal");
        tabelSenjata.addColumn("Keterangan");
        dataTable.setModel(tabelSenjata);
        
        Connection conn = Config.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "select * from senjata";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
                tabelSenjata.addRow(new Object[]{
                    res.getString("id"),
                    res.getString("nama"),
                    res.getString("jenis"),
                    res.getString("magazine"),
                    res.getString("tanggal"),
                    res.getString("keterangan")
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    
    public void ClearForm(){
                id_field.setText("");
                nama_field.setText("");
                jenis.setSelectedIndex(0);
                magazine.setSelectedIndex(0);
                jDateChooser1.setDate(null);
                keterangan.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        keterangan = new javax.swing.ButtonGroup();
        Judul = new javax.swing.JLabel();
        id_senjata = new javax.swing.JLabel();
        nama_senjata = new javax.swing.JLabel();
        jenis_senjata = new javax.swing.JLabel();
        jumlah_magazine = new javax.swing.JLabel();
        tanggal = new javax.swing.JLabel();
        labelKeterangan = new javax.swing.JLabel();
        id_field = new javax.swing.JTextField();
        nama_field = new javax.swing.JTextField();
        jenis = new javax.swing.JComboBox<>();
        magazine = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        masuk = new javax.swing.JRadioButton();
        keluar = new javax.swing.JRadioButton();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        dataSenjata = new javax.swing.JLabel();
        btnCetak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(31, 41, 55));

        Judul.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        Judul.setText("Aplikasi Inventory Senjata");

        id_senjata.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        id_senjata.setText("ID Senjata");

        nama_senjata.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nama_senjata.setText("Nama Senjata");

        jenis_senjata.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jenis_senjata.setText("Jenis Senjata");

        jumlah_magazine.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jumlah_magazine.setText("Jumlah Magazine");

        tanggal.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tanggal.setText("Tanggal");

        labelKeterangan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labelKeterangan.setText("Keterangan");

        id_field.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        nama_field.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jenis.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rifles", "Sniper Rifles", "Machine Guns", "Grenade Launcher", "Mortir", "Pistols", "Shotguns", "Submachine Guns" }));

        magazine.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        magazine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));

        jDateChooser1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        keterangan.add(masuk);
        masuk.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        masuk.setText("Senjata Masuk");

        keterangan.add(keluar);
        keluar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        keluar.setText("Senjata Keluar");

        btnTambah.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        dataTable.setBackground(new java.awt.Color(31, 41, 55));
        dataTable.setForeground(new java.awt.Color(255, 255, 255));
        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Jenis", "Jumlah Magazine", "Tanggal", "Keterangan"
            }
        ));
        dataTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dataTable);

        dataSenjata.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        dataSenjata.setText("Data Senjata");

        btnCetak.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnCetak.setText("Print");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Judul)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id_senjata)
                            .addComponent(labelKeterangan)
                            .addComponent(tanggal)
                            .addComponent(jumlah_magazine)
                            .addComponent(jenis_senjata)
                            .addComponent(nama_senjata))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(magazine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(id_field)
                                .addComponent(nama_field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(keluar)
                                .addGap(18, 18, 18)
                                .addComponent(masuk))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTambah)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus)
                        .addGap(18, 18, 18)
                        .addComponent(btnReset)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dataSenjata)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCetak)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(Judul)
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id_senjata)
                            .addComponent(id_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nama_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nama_senjata))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jenis_senjata)
                            .addComponent(jenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jumlah_magazine)
                            .addComponent(magazine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tanggal)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelKeterangan)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(keluar)
                                .addComponent(masuk)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTambah)
                            .addComponent(btnEdit)
                            .addComponent(btnHapus)
                            .addComponent(btnReset)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dataSenjata)
                            .addComponent(btnCetak))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        // format tanggal
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
        String date = dFormat.format(jDateChooser1.getDate());
        
        //format keterangan
        String keterangan ="";
        if(masuk.isSelected()){
            keterangan = masuk.getText();
        } else {
            keterangan = keluar.getText();
        }
        
        //blok tambah data
        try {
            
            Connection conn = Config.getConnection();
            
            PreparedStatement stmt = conn.prepareStatement("INSERT INTO senjata (id, nama, jenis, magazine, tanggal, keterangan) VALUES (?,?,?,?,?,?)");
                        stmt.setString(1, id_field.getText());
                        stmt.setString(2, nama_field.getText());
                        stmt.setObject(3, jenis.getSelectedItem());
                        stmt.setObject(4, magazine.getSelectedItem());
                        stmt.setString(5, date);
                        stmt.setString(6, keterangan);
                        stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            ShowData();
            ClearForm();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        
        // format tanggal
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
        String date = dFormat.format(jDateChooser1.getDate());
        
        //format keterangan
        String keterangan ="";
        if(masuk.isSelected()){
            keterangan = masuk.getText();
        } else {
            keterangan = keluar.getText();
        }
        try{
            Connection conn = Config.getConnection();
            PreparedStatement stmt = conn.prepareStatement("UPDATE senjata SET id=?, nama=?, jenis=?, magazine=?, tanggal=?, keterangan=? WHERE id=?");
            stmt.setString(1, id_field.getText());
            stmt.setString(2, nama_field.getText());
            stmt.setObject(3, jenis.getSelectedItem());
            stmt.setObject(4, magazine.getSelectedItem());
            stmt.setString(5, date);
            stmt.setString(6, keterangan);
            stmt.setString(7, id_field.getText());
            
            stmt.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Data Berhasil Diedit");
            ShowData();
            ClearForm();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void dataTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataTableMouseClicked
        // TODO add your handling code here:
       try {
        int baris = dataTable.getSelectedRow();
        
        id_field.setText(tabelSenjata.getValueAt(baris, 0).toString());
        nama_field.setText(tabelSenjata.getValueAt(baris, 1).toString());
        jenis.setSelectedItem(tabelSenjata.getValueAt(baris, 2).toString());
        magazine.setSelectedItem(tabelSenjata.getValueAt(baris, 3).toString());
        Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)tabelSenjata.getValueAt(baris, 4));
        jDateChooser1.setDate(date);
        
        String keterangan;
           keterangan = tabelSenjata.getValueAt(baris, 5).toString();
        if("Senjata Masuk".equals(keterangan)){
            masuk.setSelected(true);
        } else {
            keluar.setSelected(true);
        }
        } catch (ParseException ex) {
            Logger.getLogger(FormSenjata.class.getName()).log(Level.SEVERE, null, ex);
        }
    
        
    }//GEN-LAST:event_dataTableMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        Connection conn = Config.getConnection();
        int confirm = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin menghapus data tersebut?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (confirm == 0){
            try {
                java.sql.PreparedStatement stmt = conn.prepareStatement("DELETE from senjata WHERE id ='" + id_field.getText() + "'");
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                ShowData();
                ClearForm();
            }catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        ClearForm();
        id_field.requestFocus();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        try {
            // TODO add your handling code here:
            dataTable.print(PrintMode.FIT_WIDTH, new MessageFormat("DATA SENJATA"),null);
        } catch (PrinterException ex) {
            Logger.getLogger(FormSenjata.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSenjata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSenjata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSenjata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSenjata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FormSenjata().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Judul;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel dataSenjata;
    private javax.swing.JTable dataTable;
    private javax.swing.JTextField id_field;
    private javax.swing.JLabel id_senjata;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JLabel jenis_senjata;
    private javax.swing.JLabel jumlah_magazine;
    private javax.swing.JRadioButton keluar;
    private javax.swing.ButtonGroup keterangan;
    private javax.swing.JLabel labelKeterangan;
    private javax.swing.JComboBox<String> magazine;
    private javax.swing.JRadioButton masuk;
    private javax.swing.JTextField nama_field;
    private javax.swing.JLabel nama_senjata;
    private javax.swing.JLabel tanggal;
    // End of variables declaration//GEN-END:variables
}
